### PR TITLE
fix(chips): mobile select

### LINKED ISSUE #1044: [BUG] TdChips with Autocomplete in mobile does not select
#### Bug Report
Autocomplete options in mobile doesn't select.

Teradata issue screen shot giff

#### Which version of Angular and Material, and which browser and OS does this issue affect?

I'm using the latest release 1.0.0-rc.1

### PR DESCRIPTION
**Pull request by felipeik**
## Description
Fixed select on Chips Autocomplete on mobile devices.
Closes #1044

### What's included?
* Modified: `src/platform/core/chips/chips.component.ts`

* Reason of the bug: `touchend` events is canceling `click` events on mobile
* Fix explanation: Added debounceTime to prevent both events from being fired together

#### Test Steps
- [ ] Go to Chips demo page
- [ ] Try selecting autocomplete on desktop
- [ ] Try selecting autocomplete on mobile view
- [ ] With ng serve --host 0.0.0.0, try on a real phone opening the application on port 4200

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

### CODE REVIEW

**Comment by felipeik** [comment]
BTW, I removed the `touchend` event altogether and the application worked on a real iPhone/Chrome device.

I don't know if the `touchend` evnt is necessary for other OS or browsers.

File: src/platform/core/chips/chips.component.ts [hunk 1]
```diff
@@ -722,6 +722,7 @@ export class TdChipsComponent extends _TdChipsMixinBase implements IControlValue
         fromEvent(this._document, 'click'),
         fromEvent(this._document, 'touchend'),
       ).pipe(
+        debounceTime(this.debounce),
```
Comment (emoralesb05) [inline src/platform/core/chips/chips.component.ts]: We probably should have a different constant (with 100-200 ms) for the debounce since this `debounce` variable is more about the key presses and opening the menu and its configurable, so it will be weird if they add a `1000` or `2000` debounce and it takes 1 - 2 seconds to select it.

**Comment by emoralesb05** [comment]
Thanks for the investigative work! Just left a small comment 🎉

File: src/platform/core/chips/chips.component.ts (hunk 1 above)
Comment (felipeik) [reply src/platform/core/chips/chips.component.ts]: just created a `this._touchendDebounce = 100` at the top of the file

**Comment by felipeik** [comment]
Hi @emoralesb05 , I just pushed the fix to the comment!
