### PR TITLE
fix(dynamic-forms): update template when manually adding errors to controls

### LINKED ISSUE #1130: DynamicForm doesn't show custom errors after submit
As discussed on gitter I'm unable to display custom errors in dynamic form components
via `control.setErrors({...})` (eg. when I receive server-side validation errors) 
until the input get focus or user clicks on the input with error.

errors have been set via the suggested TemplatePortal:

```
<ng-template let-element ngFor [ngForOf]="elements">
  <ng-template let-control="control" [tdDynamicFormsError]="element.name">
...
```

I've made a StackBlitz template: 

https://stackblitz.com/edit/covalent-dynamic-forms-2jypqc

showing the error and a pure Material/Angular solution with FormGroup.

It seems to be a change detection issue.

### PR DESCRIPTION
**Pull request by felipeik**
## Description
Display Dynamic Forms error messages when adding error to controls through control.setErrors(...).

### What's included?
- Added Status Changes subscription on controls so we can detect changes when updating the control from outside
- New documentation "Manual Validators"
- Unit test

#### Test Steps

- [ ] `npm run serve`
- [ ] Open http://localhost:4200/#/components/dynamic-forms
- [ ] Scroll to "Manual Validators" (new section)
- [ ] Type 'asdgg' and click on Submit button
- [ ] See error message "Only vowel characters. Do not use any consonants."
- [ ] Type "aeiou" and click on Submit button
- [ ] Error message disapears
- [ ] View example source code

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

##### Screenshots or link to StackBlitz/Plunker

This PR fixes #1130

### CODE REVIEW

File: src/platform/dynamic-forms/dynamic-forms.component.ts [hunk 1]
```diff
@@ -178,4 +179,10 @@ export class TdDynamicFormsComponent implements AfterContentInit {
       this.dynamicForm.removeControl(elem.name);
     });
   }
+
+  // Updates component when manually adding errors to controls
+  private _subscribeToControlStatusChanges(elementName: string): void {
+    const control: AbstractControl = this.controls[elementName];
+    control.statusChanges.subscribe(() => this._changeDetectorRef.markForCheck());
```
Comment (emoralesb05) [inline src/platform/dynamic-forms/dynamic-forms.component.ts]: We need to unsubscribe from the observable when elements get removed or the component gets destroyed since there will be memory leaks if we dont.

Comment (felipeik) [reply src/platform/dynamic-forms/dynamic-forms.component.ts]: hi @emoralesb05 , I just pushed an enhancement to the control subscription.
